
project_id = "gqjoebrphojntidztfyd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
api_port = 54326

[functions.content-harvester]
verify_jwt = false

[functions.process-content-source]
verify_jwt = false

[functions.test-rss-feed]
verify_jwt = false

[edge-runtime]
enabled = true
port = 54327
inspector_port = 54328

[analytics]
enabled = false
port = 54329
vector_port = 54330
backend = "postgres"
